
// Unit tests for: RootLayout

import React from 'react'
import { render } from '@testing-library/react';
import RootLayout, { metadata } from '../../../src/app/layout';
import "@testing-library/jest-dom";

describe('RootLayout() RootLayout method', () => {
  // Happy Path Tests
  describe('Happy Path', () => {
    it('should render children correctly', () => {
      // This test checks if the RootLayout renders its children properly.
      const { getByText } = render(
        <RootLayout>
          <div>Test Child</div>
        </RootLayout>
      );
      expect(getByText('Test Child')).toBeInTheDocument();
    });

    it('should apply the correct classes to the body element', () => {
      // This test verifies that the body element has the correct classes applied.
      const { container } = render(
        <RootLayout>
          <div>Test Child</div>
        </RootLayout>
      );
      const body = container.querySelector('body');
      expect(body).toHaveClass('antialiased');
      expect(body).toHaveClass('--font-geist-sans');
      expect(body).toHaveClass('--font-geist-mono');
    });

    it('should have the correct metadata', () => {
      // This test checks if the metadata is correctly defined.
      expect(metadata.title).toBe('Create Next App');
      expect(metadata.description).toBe('Generated by create next app');
    });
  });

  // Edge Case Tests
  describe('Edge Cases', () => {
    it('should handle no children gracefully', () => {
      // This test ensures that the component can handle being rendered without children.
      const { container } = render(<RootLayout>{null}</RootLayout>);
      const body = container.querySelector('body');
      expect(body).toBeInTheDocument();
      expect(body?.children.length).toBe(0);
    });

    it('should handle undefined children gracefully', () => {
      // This test ensures that the component can handle undefined children.
      const { container } = render(<RootLayout>{undefined}</RootLayout>);
      const body = container.querySelector('body');
      expect(body).toBeInTheDocument();
      expect(body?.children.length).toBe(0);
    });

    it('should handle empty string children gracefully', () => {
      // This test ensures that the component can handle empty string children.
      const { container } = render(<RootLayout>{''}</RootLayout>);
      const body = container.querySelector('body');
      expect(body).toBeInTheDocument();
      expect(body?.textContent).toBe('');
    });
  });
});

// End of unit tests for: RootLayout
